import '@styles/globals.css'
import {children} from 'react';



export const metadata = {
  title: 'Scrape Me',
  description: 'Generated by create next app',
}

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
    <head></head>
    <body className="archive post-type-archive post-type-archive-product woocommerce woocommerce-page woocommerce-no-js right-sidebar woocommerce-active storefront">
    {children}
    </body>
    </html>
  )
}

export default RootLayout;
